version: "3.9"

services:
  db:
    image: postgres:15
    container_name: insightengine_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9250
      POSTGRES_DB: insightengine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: insightengine_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:9250@db:5432/insightengine

volumes:
  postgres_data: